name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  dependencies_macos-latest:
    name: Dependencies for latest MacOS
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install sqlite
  dependencies_ubuntu-latest:
    name: Dependencies for latest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt ci g++-11 sqlite
  ci:
    name: Continuous integration on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: dependencies_${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
